#!/bin/bash

WDIR=`dirname $0`
FF=$WDIR/firefox/missinge/package.json
CH=$WDIR/chrome/manifest.json
SF=$WDIR/missinge.safariextension/Info.plist

sed -e 's/"version": "[^"]*"/"version": "'$1'"/' $FF > $FF.new
mv $FF.new $FF

sed -e 's/"version":     "[^"]*"/"version":     "'$1'"/' $CH > $CH.new
mv $CH.new $CH

sed -e '/CFBundleShortVersionString<\/key>/{
N
s/CFBundleShortVersionString<\/key>\n\t<string>[^<]*/CFBundleShortVersionString<\/key>\n\t<string>'$1'/
}' $SF > $SF.new
sed -e '/CFBundleVersion<\/key>/{
N
s/CFBundleVersion<\/key>\n\t<string>[^<]*/CFBundleVersion<\/key>\n\t<string>'$2'/
}' $SF.new > $SF
rm $SF.new

