<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" dir="ltr">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="tumblr,missinge,missing,e,feature,features,blog,blogging" />
<meta name="description" content="Missing e - The unofficial browser extension for Tumblr!"/>
<meta name="author" content="Jeremy Cutler" />
<meta name="robots" content="FOLLOW,INDEX" />
<title>Submit Bug Report - Missing e - The original browser extension for Tumblr!</title>
<link href='http://fonts.googleapis.com/css?family=Kreon:300,400,700' rel='stylesheet' type='text/css'>
<link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
<link rel="icon" href="/favicon.png" type="image/x-icon" />
<script type="text/javascript" src="browser.js"></script>
<script type="text/javascript" src="jquery-1.7.2.min.js"></script>
<link rel="stylesheet" type="text/css" href="reset.css" />
<link rel="stylesheet" type="text/css" href="sitestyles.css" />
<?php

$submission = isset($_REQUEST['bugsubmission']);

if ($submission) {
   $host = $_SERVER['REMOTE_ADDR'];
   if (isset($_SERVER['REMOTE_HOST'])) {
      $host = $_SERVER['REMOTE_HOST'];
   }
   if (isset($_REQUEST['missingeversion']) && !empty($_REQUEST['missingeversion'])) {
      $version = $_REQUEST['missingeversion'];
   }
   else {
      $version = 'version unknown';
   }
   $to = $_REQUEST['thec'];
   $subject = "Bug Report (" . $_REQUEST['reason'] . ") " . $_REQUEST['timestamp'];
   $message = "This message was automatically generated by the Missing e bug " .
      "report tool at http://missing-e.com (from " . $host . ")\n\n" .
      "If this message was sent to you in error, please ignore it.\n\n" .
      "==========\n Info\n==========\n\n" .
      $_REQUEST['timestamp'] . "\n\n" .
      "Bug Report (" . $_REQUEST['reason'] . ")\n\n" .
      "From: " . $_REQUEST['thec'] . " (" . $host . ")\n\n" .
      "Missing e " . $version . "\n\n" .
      "OS: " . $_REQUEST['os'] . "\n" .
      "Browser: " . $_REQUEST['browser'] . " " . $_REQUEST['browserversion'] . "\n\n" .
      $_SERVER['HTTP_USER_AGENT'] . "\n\n" .
      "==========\n Report\n==========\n\n" .
      $_REQUEST['report'] . "\n\n" .
      "==========\n Settings\n==========\n\n" .
      $_REQUEST['options'];
   $headers = 'From: Missing e Bug Report <bugreport@missing-e.com>' . "\r\n" .
      'Cc: Missing e Bug Report <bugreport@missing-e.com>' . "\r\n" .
      'Reply-To: ' . $_REQUEST['thec'] . "\r\n" .
      'X-Mailer: Missing e Bug Report Tool v1.1 PHP/' . phpversion();
   mail($to, $subject, $message, $headers);
}

if (!$submission) {
   if (isset($_REQUEST['reason'])) {
      $inputReason = $_REQUEST['reason'];
   }
   else {
      $inputReason = "OTHER";
   }
?>
<script type="text/javascript">
<!--

var updateCheck;
var extResponded;

function currentTimestamp() {
   var now = new Date();
   var tz = 0.0 - now.getTimezoneOffset();
   tz = tz / 60;
   var month = (now.getMonth()+1);
   if (month < 10) {
      month = "0" + month;
   }
   var date = now.getDate();
   if (date < 10) {
      date = "0" + date;
   }
   return now.getFullYear() + "-" + month + "-" + date + " " +
      now.toTimeString();
}

function validateEmail(email) { 
   var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
   return re.test(email);
}

function receiveInfo(msg) {
   var earliestVer = [2,9,0];
   var supported = false;
   if (msg.data.response === "extensionInfo") {
      if (msg.data.info && msg.data.info.version) {
         $('#missingeversion').val(msg.data.info.version);
         $('#missingeversion_text').text(msg.data.info.version);
      }
      window.postMessage({"MissingE":true, "src":"site", "request":"options"},
                         "http://missing-e.com");
   }
   else if (msg.data.response === "options") {
      $('#options').val(msg.data.options);
   }
}

function checkUpdate(count) {
   if (!count) { count = 1; }

   if (window.extResponded) {
      return;
   }
   else if (count > 20) {
      return;
   }
   else {
      count++;
      window.postMessage({"MissingE":true, "src":"site",
                          "request":"extensionInfo"},
                         "http://missing-e.com");
      updateCheck = setTimeout(function(){ checkUpdate(count); }, 500);
   }
}

jQuery(document).ready(function($) {
   window.extResponded = false;
   window.addEventListener("message", function(e) {
      if (e.data && e.data.MissingE && e.data.src === "extension") {
         window.extResponded = true;
         receiveInfo(e);
      }
   }, false);
   window.postMessage({"MissingE":true, "src":"site",
                       "request":"extensionInfo"},
                      "http://missing-e.com");

   updateCheck = setTimeout(checkUpdate, 500);

   $('#os').val(BrowserDetect.OS);
   $('#os_text').text(BrowserDetect.OS);

   $('#browser').val(BrowserDetect.browser);
   $('#browser_text').text(BrowserDetect.browser);

   $('#browserversion').val(BrowserDetect.version);
   $('#browserversion_text').text(BrowserDetect.version);
   
   $('#bugform').submit(function() {
      var errors = [];
      var form = $(this);
      var report;
      if (!validateEmail(form.find('#thec').val())) {
         errors.push("! Please enter a valid email address");
      }
      report = form.find('#report').val();
      report = report.replace(/^\s+/,'').replace(/\s+$/,'');
      if (report.length < 32) {
         errors.push("! Include a detailed description of the problem");
      }
      if (errors.length > 0) {
         alert(errors.join("\n"));
         return false;
      }
      $('#timestamp').val(currentTimestamp());
   });
});

-->
</script>
<?php

} //submission

?>
<body id="submitbug">
<header>
 <nav>
  <div id="nav_bar">
   <a href="/" id="home_nav"><span id="home_navbg"></span><span class="subtext">HOME</span><img src="images/missinge100.png" alt="Home" /></a>
   <div id="nav_links">
    <a href="features" class="features_nav">FEATURES<span class="subtext">WHAT IT'S FOR.</span></a>
    <a href="faq" class="faq_nav">FAQ<span class="subtext">QUESTIONS?</span></a>
    <a href="troubleshoot" class="problems_nav selected_nav">PROBLEMS<span class="subtext">LET'S TROUBLESHOOT!</span></a>
    <a href="http://blog.missing-e.com" class="blog_nav">BLOG<span class="subtext">STAY UPDATED.</span></a>
    <a href="https://www.paypal.com/ca/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=EGQCRBB2BH5U8" class="donate_nav">DONATE<span class="subtext">SUPPORT MISSING E!</span></a>
   </div>
  </div>
 </nav>
 <div id="banner">
  <div id="icon_ribbon">
   <div id="page_icon">
    <img src="images/bugspray.png" alt="Submit Bug Report" style="margin-top:5px;opacity:0.95;" />
   </div>
  </div>
  <div id="icon_ribbon_rem"></div>
  <div id="banner_text">
   <hgroup>
    <h1>Report a bug.</h1>
    <h2>Because spraying the code with repellent doesn't work!</h2>
   </hgroup>
  </div>
 </div>
</header>
<div id="ad_title">Ads by Google. Missing e does not endorse and disclaims liability for any product, manufacturer, distributor, service or service provider mentioned.</div>
<div id="ad">
 <div id="ad_sidetitle"></div>
 <script type="text/javascript">
  <!--
   google_ad_client = "ca-pub-3604999147338055";
   /* New Site */
   google_ad_slot = "6340955762";
   google_ad_width = 728;
   google_ad_height = 90;
  //-->
 </script>
 <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
</div>
<div id="main_content">
<?php

if ($submission) {

?>
 <div id="bugreport_done">
  <h1>Done!</h1>
  <p>Thanks for submitting a bug report. You'll be contacted soon!</p>
  <a href="/" class="button greenbutton">Home</a>
 </div>
<?php

}
else {

?>
 <form id="bugform" action="submitbug" method="post">
  <input type="hidden" id="bugsubmission" name="bugsubmission" value="1" />
  <input type="hidden" id="options" name="options" value="" />
  <input type="hidden" id="timestamp" name="timestamp" value="" />
  <input type="hidden" id="reason" name="reason" value="<?=$inputReason;?>" />
  <input type="hidden" id="os" name="os" value="" />
  <input type="hidden" id="browser" name="browser" value="" />
  <input type="hidden" id="browserversion" name="browserversion" value="" />
  <input type="hidden" id="missingeversion" name="missingeversion" value="" />
  <h1>Submit Bug Report</h1>
  <div class="bugreport_box wide_postit">
   <div class="step_icon unnumberedstep"></div>
   <hgroup>
    <h2>Your Computer</h2>
   </hgroup>
   <p><strong>Operating System:</strong> <span id="os_text"></span></p>
   <p><strong>Browser:</strong> <span id="browser_text"></span></p>
   <p><strong>Browser Version:</strong> <span id="browserversion_text"></span></p>
   <p><strong>Missing e Version:</strong> <span id="missingeversion_text"></span></p>
  </div>
  <div class="bugreport_box">
   <div class="step_icon unnumberedstep"></div>
   <hgroup>
    <h2>The Problem You Are Having</h2>
   </hgroup>
    <p><strong>Problem Type:</strong> <?=$inputReason;?></p>
    <p style="margin-top:15px" class="bugreport_msg">Please describe the problem:</p>
    <textarea id="report" name="report" placeholder="What, exactly, is the problem? What were you doing when the problem came up? What steps are necessary to reproduce the problem?"></textarea>
  </div>
  <div class="bugreport_box">
   <div class="step_icon unnumberedstep"></div>
   <hgroup>
    <h2>Contact Email</h2>
   </hgroup>
   <p class="bugreport_msg">Required. Your email address will not be used except for communicating with you for bug investigation.</p>
   <div class="input_box"><input type="text" name="thec" id="thec" style="width:200px" placeholder="you@somewhere.com" /></div>
  </div>
  <div id="formbuttons"><button type="submit" title="Send" class="button greenbutton"><span>Send</span></button><a href="troubleshoot" title="Cancel" class="button silverbutton">Cancel</a></div>
 </form>
<?php

}

?>
</div>
<div id="footer_container">
 <div id="footer">
  &copy; 2012, Jeremy Cutler<br />
  <small>An open-source project released under <a class="link" href="http://www.gnu.org/licenses/gpl.html" title="GPL v3 License">GPL v3</a></small>
  <a class="button silverbutton" href="http://blog.missing-e.com" title="Missing e on Tumblr">Follow Missing e on Tumblr</a>
 </div>
</div>
</body>
</html>
